#ifndef MATATAKUMACHINAMI_H
#define	MATATAKUMACHINAMI_H

music machinami = {125, 44,
{
	{C, 8, EIGHTH_NOTE},
	{F, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	{C, 8, EIGHTH_NOTE},
	{F, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	{C, 8, EIGHTH_NOTE},
	{E, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	{C, 8, EIGHTH_NOTE},
	{E, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	
	{F, 16, SIXTEENTH_NOTE},
	{D, 16, SIXTEENTH_NOTE},
	{A_, 8, SIXTEENTH_NOTE},//Bhuratto
	{F, 8, SIXTEENTH_NOTE},
	{F, 16, SIXTEENTH_NOTE},
	{D, 16, SIXTEENTH_NOTE},
	{A_, 8, SIXTEENTH_NOTE},//Bhuratto
	{F, 8, SIXTEENTH_NOTE},
	{E, 16, SIXTEENTH_NOTE},
	{C, 16, SIXTEENTH_NOTE},
	{G, 8, SIXTEENTH_NOTE},
	{E, 8, SIXTEENTH_NOTE},
	{C, 8, SIXTEENTH_NOTE},
	{E, 8, SIXTEENTH_NOTE},
	{G, 8, SIXTEENTH_NOTE},
	{C, 16, SIXTEENTH_NOTE},

	{C, 8, EIGHTH_NOTE},
	{F, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	{C, 8, EIGHTH_NOTE},
	{F, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	{C, 8, EIGHTH_NOTE},
	{E, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	{C, 8, EIGHTH_NOTE},
	{E, 8, SIXTEENTH_NOTE},
	{A, 8, SIXTEENTH_NOTE},
	
	{A, 8, 8},
	{G, 8, 8},
	{F, 8, 8},
	{E, 8, HALF}
}
};
#endif	/* MATATAKUMACHINAMI_H */

